sudo: false

language:
  - python

python:
  - 3.6

install:
  - pip install -r src/pi_sample_duration/requirements.txt

script:
  - pycodestyle src/pi_sample_duration
  - pytest --verbose --capture=no
  - pip install src/pi_sample_duration

notifications:
  email: false
